name = "stellorbitnet-cms"
main = "src/worker.js"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"

[vars]
GITHUB_OWNER = "stellorbit"
GITHUB_REPO = "stellorbitnet-ver2"
GITHUB_BRANCH = "main"
